
# All-blog Settings
host:   http://localhost:3000
posts:  /posts
count:  12
title:  MicrowaveJS Blog
desc:   An example MicrowaveJS blog that you'll want to read again and again!
author: Blog Author
forcehost: true

# Display Settings
next:  Newer Posts
prev:  Older Posts
posttimeformat: MMMM d, yyyy

# DISQUS Settings
comments:    true
disqusname:  testblog

# Google Analytics Settings
analytics:        UA-XXXXXXXX-X
analyticsdomain:  localhost:3000

